### ISSUE TITLE
ARM64 Device Incompatibility 

### ISSUE THREAD

**Issue by utilityfog** [iterativecloud/jupyter-notebook-chatcompletion#10]
When running this extension on an ARM64 device, such as Macbook Pro M3 Max, I always receive the error below when passing a cell's contents to the extension's chat completion API handler:
```
Exception has occurred: SyntaxError: Expected ',' or '}' after property value in JSON at position 147 (line 1 column 148)
  at JSON.parse (<anonymous>)
    at streamChatCompletion (/Users/user/.vscode/extensions/iterativecloud.notebook-chatcompletion-0.0.22/out/streamUtils.js:19:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at bufferWholeChunks (/Users/user/.vscode/extensions/iterativecloud.notebook-chatcompletion-0.0.22/out/streamUtils.js:47:22)
    at streamResponse (/Users/user/.vscode/extensions/iterativecloud.notebook-chatcompletion-0.0.22/out/completion.js:19:20)
    at generateCompletion (/Users/user/.vscode/extensions/iterativecloud.notebook-chatcompletion-0.0.22/out/completion.js:147:12)
    at /Users/user/.vscode/extensions/iterativecloud.notebook-chatcompletion-0.0.22/out/extension.js:51:28
```
I tried debugging the extension itself, but eventually gave up. It seems that this extension is incompatible with ARM 64 devices as of now. Please have a look!

**Comment by AlexandreDeRiemaecker** [comment]
The fix for this issue and update of dependencies are now rolled out to the regular release version of the extension.

**Comment by utilityfog** [comment]
Hi Alex! Thank you for the prompt fix of the bug. I have verified that cell completion now works correctly on my device, which is an ARM64 mac.
